SuperDevices.WebApp/Models/ErrorViewModel.cs
namespace SuperDevices.WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperDevices.WebApp/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuperDevices.Domain.Entities;
using SuperDevices.DataAccess.Context;
using SuperDevices.Domain.Repository;
using SuperDevices.DataAccess.Repository;
using SuperDevices.Domain.Dtos;
using AutoMapper;
using System.Security.Claims;

namespace SuperDevices.WebApp.Controllers
{
    [Authorize]
    public class DevicesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public DevicesController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        // GET: Devices
        public async Task<IActionResult> Index()
        {
            if (_unitOfWork.Device.IsNull())
                return Problem("Entity set 'ApplicationDbContext.Devices'  is null.");


            var list = await _unitOfWork.Device.GetAllAsync();

            var listDtos = DeviceDtoFactory.CreateCollectionDtofromModelCollection(_mapper, list);


            return View(listDtos);
        }

        // GET: Devices/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
                return NotFound();
            
            if (_unitOfWork.Device.IsNull())
                return Problem("Entity set 'ApplicationDbContext.Devices'  is null.");


            var device = await _unitOfWork.Device.GetByIdAsync(id.Value);

            if (device == null)
                return NotFound();

            var deviceDto =  DeviceDtoFactory.CreateDtofromModel(_mapper, device);

            return View(deviceDto);
        }

        // GET: Devices/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Devices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,SerialNumber,Id")] DeviceDto deviceDto)
        {
            if (ModelState.IsValid)
            {
                deviceDto.Id = Guid.NewGuid();

                var userId = this.User.FindFirstValue(ClaimTypes.Name);
                if (String.IsNullOrEmpty(userId))
                    return Problem("User is null.");
                var device = DeviceDtoFactory.CreateModelfromDto(_mapper, deviceDto);
                _unitOfWork.Device.Add(device, userId);

                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(deviceDto);
        }

        // GET: Devices/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            if (_unitOfWork.Device.IsNull())
                return Problem("Entity set 'ApplicationDbContext.Devices'  is null.");

            var device = await _unitOfWork.Device.GetByIdAsync(id.Value);

            

            if (device == null)
                return NotFound();

            var deviceDto = DeviceDtoFactory.CreateDtofromModel(_mapper, device);

            return View(deviceDto);
        }

        // POST: Devices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Name,SerialNumber,Id")] DeviceDto deviceDto)
        {
            if (id != deviceDto.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var userId = this.User.FindFirstValue(ClaimTypes.Name);
                    if (String.IsNullOrEmpty(userId))
                        return Problem("User is null.");

                    var device = await _unitOfWork.Device.GetByIdAsync(id);
                    if (device == null)
                        return NotFound();

                    DeviceDtoFactory.UpdateModelfromDto(_mapper, device, deviceDto);
                    _unitOfWork.Device.Update(device, userId);
                    await _unitOfWork.SaveAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_unitOfWork.Device.Exists(deviceDto.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deviceDto);
        }

        // GET: Devices/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            if (_unitOfWork.Device.IsNull())
                return Problem("Entity set 'ApplicationDbContext.Devices'  is null.");

            var device = await _unitOfWork.Device.GetByIdAsync(id.Value);

            if (device == null)
                return NotFound();
            
            var deviceDto = DeviceDtoFactory.CreateDtofromModel(_mapper, device);

            return View(deviceDto);
        }

        // POST: Devices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if(_unitOfWork.Device.IsNull())
                return Problem("Entity set 'ApplicationDbContext.Devices'  is null.");

            var device = await _unitOfWork.Device.GetByIdAsync(id);

            if (device != null)
            {
                _unitOfWork.Device.Remove(device);
            }

            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

SuperDevices.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SuperDevices.WebApp.Models;
using System.Diagnostics;

namespace SuperDevices.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperDevices.WebApp/Views/Devices/Create.cshtml
@model SuperDevices.Domain.Dtos.DeviceDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Device</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperDevices.WebApp/Views/Devices/Delete.cshtml
@model SuperDevices.Domain.Dtos.DeviceDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Device</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateInfo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EditorInfo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EditorInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Version)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Version)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperDevices.WebApp/Views/Devices/Details.cshtml
@model SuperDevices.Domain.Dtos.DeviceDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Device</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EditorInfo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EditorInfo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Version)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Version)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SuperDevices.WebApp/Views/Devices/Edit.cshtml
@model SuperDevices.Domain.Dtos.DeviceDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Device</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperDevices.WebApp/Views/Devices/Index.cshtml
@model IEnumerable<SuperDevices.Domain.Dtos.DeviceDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SuperDevices.WebApp/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2>This is Super App</h2>

    @if (SignInManager.IsSignedIn(User))
    {
        <p>You are logged in! You can use the function <a asp-area="" asp-controller="Devices" asp-action="Index">Devices</a></p> 
    }
    else
    {
        <p>Register/Log in to use the function Devices</p>
    }


    
</div>

SuperDevices.WebApp/Views/Shared/_DeviceButtonPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <a class="nav-link text-dark" asp-area="" asp-controller="Devices" asp-action="Index">Devices</a>
}
else
{
    <a class="nav-link text-dark" asp-area="" asp-controller="Devices" asp-action="Index">Devices - log in required!</a>
}

SuperDevices.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SuperDevices.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home page</a>
                        </li>
                        <li class="nav-item">
                            <partial name="_DeviceButtonPartial" />
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SuperApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>